nim_mission_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: nim.controller.mission:indexAction
        _sylius:
            template: NIMWebBundle:Mission:index.html.twig
            paginate: $page
            sortable: $sorting
            filterable: $criteria

nim_mission_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: nim.controller.mission:createAction
        _sylius:
            template: NIMWebBundle:Mission:create.html.twig
            redirect: nim_mission_show

nim_mission_update:
    pattern: /{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: nim.controller.mission:updateAction
        _sylius:
            template: NIMWebBundle:Mission:update.html.twig
            redirect: nim_mission_show

nim_mission_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: nim.controller.mission:showAction
        _sylius:
            template: NIMWebBundle:Mission:show.html.twig

nim_mission_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: nim.controller.mission:deleteAction
        _sylius:
            redirect: nim_mission_index
            template: NIMWebBundle:Misc:delete.html.twig
